[package]
name = "txnos-kernel"
version = "0.0.1"
edition = "2024"

[dependencies]
actix-web = { version = "4", features=["openssl"] }
openssl = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
